
enable_telemetry    = true
resource_group_name = "lumen-avd-rg-03"
location            = "EastUS2"
name                = "aks-02"
keyvault_name                                 = "lumen-avd-kv-01"
object_id                                     = "08afb591-fb58-46c1-b797-76688967a5cf"
tenant                                    = "c925fe9d-30b1-4191-acbf-4109845df16f"
storage_account_name                          = "lumenstorage1234"
domain_name                                   = "privatelink.wvd.microsoft.com"
virtual_desktop_host_pool_load_balancer_type  = "DepthFirst"
virtual_desktop_host_pool_name                = "avdhostpool-1"
virtual_desktop_host_pool_type                = "Pooled"
virtual_desktop_application_group_name        = "applicationgroup-1"
virtual_desktop_application_group_type        = "Desktop"
virtual_desktop_workspace_name                = "AVDWorkspace"
operationalinsights_workspace_name            = "OperationalInsightsWorkspaceLumen"
virtual_desktop_host_pool_resource_group_name = "AVD"
virtual_desktop_host_pool_location            = "East US"

